#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
GUARDIAN OPS (Model B: single source-of-truth in ./docs)

- ./docs/                    = project canonicals (EDIT HERE)
- ./.doc/                    = operational control room (EDIT ONLY TODO/CURRENT_STATE/LOGBOOK)
- ./.doc/canonical/derived/  = compact operational library (GENERATED by `derive`)
- ./.doc/_GUARDIAN/          = guardian manuals/rules (template)

No mirror copies in ./.doc/canonical/project/.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable, List, Optional, Tuple


# ----------------------------
# Configuration
# ----------------------------

@dataclass(frozen=True)
class GuardianPaths:
    repo_root: Path
    docs_dir: Path
    doc_root: Path
    canonical_dir: Path
    derived_dir: Path
    guardian_dir: Path
    index_file: Path
    readme_file: Path
    todo_file: Path
    current_state_file: Path
    logbook_file: Path


def default_paths() -> GuardianPaths:
    repo_root = Path(".").resolve()
    docs_dir = repo_root / "docs"
    doc_root = repo_root / ".doc"
    canonical_dir = doc_root / "canonical"
    derived_dir = canonical_dir / "derived"
    guardian_dir = doc_root / "_GUARDIAN"

    return GuardianPaths(
        repo_root=repo_root,
        docs_dir=docs_dir,
        doc_root=doc_root,
        canonical_dir=canonical_dir,
        derived_dir=derived_dir,
        guardian_dir=guardian_dir,
        index_file=doc_root / "CANONICAL_LIBRARY.md",
        readme_file=doc_root / "00_README.md",
        todo_file=doc_root / "TODO.md",
        current_state_file=doc_root / "CURRENT_STATE.md",
        logbook_file=doc_root / "LOGBOOK.md",
    )


# ----------------------------
# Canonical allowlist (project)
# ----------------------------
# NOTE: support both "versionless" and legacy "*_vX.Y.md" names via patterns.
REQUIRED_DOCS = [
    # (logical_id, human_name, preferred_filename, legacy_globs...)
    ("001", "Project Overview", "001_PROJECT_OVERVIEW.md", ["001_PROJECT_OVERVIEW_v*.md"]),
    ("002", "PDR", "002_PDR_OBSERVER.md", ["002_PDR_OBSERVER_v*.md"]),
    ("003", "PDD", "003_PDD_OBSERVER.md", ["003_PDD_OBSERVER_v*.md"]),
    ("004", "DDT DataDictionary", "004_DDT_DATADICTIONARY.md", [
        "004_DDT_DATADICTIONARY_v*.md",
        "004_DATADICTIONARY*.md",          # legacy
    ]),
    ("005", "Traceability Matrix", "005_TRACEABILITY_MATRIX.md", ["005_TRACEABILITY_MATRIX_v*.md"]),
    ("007", "Parameter Snapshot", "007_PARAMETER_SNAPSHOT.md", ["007_PARAMETER_SNAPSHOT_v*.md"]),
    ("008", "Evidence Pack", "008_EVIDENCE_PACK.md", ["008_EVIDENCE_PACK_v*.md"]),
    ("009", "Gap Register", "009_GAP_REGISTER.md", ["009_GAP_REGISTER_v*.md"]),
]

OPTIONAL_DOCS_GLOBS = [
    "000_*.md",
    "006_*.md",
    "*.pdf",
]


# ----------------------------
# Utilities
# ----------------------------

def utc_now_iso() -> str:
    return datetime.utcnow().replace(microsecond=0).isoformat() + "Z"


def sha256_bytes(data: bytes) -> str:
    h = hashlib.sha256()
    h.update(data)
    return h.hexdigest()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def write_text_if_changed(path: Path, content: str, encoding: str = "utf-8-sig") -> bool:
    """
    Anti-churn: write only if content differs.
    Returns True if file written/updated, False if no-op.
    """
    # NOTE (EOL determinism): on Windows, text-mode writes translate "\n" -> "\r\n".
    # To avoid CRLF/LF churn and Git warnings, we treat the *desired* file bytes as the
    # source of truth and write with newline="\n".
    desired_bytes = content.encode(encoding)

    if path.exists():
        try:
            existing_bytes = path.read_bytes()
            if existing_bytes == desired_bytes:
                return False
        except Exception:
            # If unreadable, overwrite (rare)
            pass
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding=encoding, newline="\n") as f:
        f.write(content)
    return True


def safe_rel(p: Path, base: Path) -> str:
    try:
        return str(p.relative_to(base)).replace("\\", "/")
    except Exception:
        return str(p).replace("\\", "/")


def find_doc(docs_dir: Path, preferred: str, legacy_globs: List[str]) -> Optional[Path]:
    """
    Resolve canonical doc path in ./docs:
      1) preferred exact filename
      2) legacy globs (deterministic: sort)
    """
    pref = docs_dir / preferred
    if pref.exists():
        return pref

    matches: List[Path] = []
    for g in legacy_globs:
        matches.extend(sorted(docs_dir.glob(g)))

    # Deterministic selection: lexicographically last is often highest version;
    # but since we are moving towards versionless naming, pick last as best-effort.
    if matches:
        return matches[-1]

    return None


def collect_project_docs(paths: GuardianPaths) -> Tuple[List[Path], List[str]]:
    """
    Returns (resolved_required_docs, missing_doc_messages)
    """
    resolved: List[Path] = []
    missing: List[str] = []

    if not paths.docs_dir.exists():
        missing.append(f"Missing docs directory: {paths.docs_dir}")
        return ([], missing)

    for doc_id, human, preferred, legacy in REQUIRED_DOCS:
        p = find_doc(paths.docs_dir, preferred, legacy)
        if p is None:
            missing.append(f"[{doc_id}] Missing required doc: {preferred} (or legacy patterns: {legacy})")
        else:
            resolved.append(p)

    return resolved, missing


def compute_fingerprint(files: Iterable[Path], base: Path) -> str:
    """
    Deterministic fingerprint over relative paths + file hashes.
    """
    items: List[Tuple[str, str]] = []
    for f in files:
        if f.is_file():
            items.append((safe_rel(f, base), sha256_file(f)))
    items.sort(key=lambda x: x[0])

    blob = json.dumps(items, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
    return sha256_bytes(blob)[:16]  # short fingerprint for readability


# ----------------------------
# Templates / Structure
# ----------------------------

README_TEMPLATE = """# .doc/ — Control Room Operativa (GUARDIAN)

Questa cartella contiene:
- **stato operativo umano** (editabile): `TODO.md`, `CURRENT_STATE.md`, `LOGBOOK.md`
- **libreria operativa derivata** (NON editare a mano): `.doc/canonical/derived/*`
- **manualistica GUARDIAN**: `.doc/_GUARDIAN/*`

Regola fondamentale:
- I canonici di progetto si editano **solo** in `./docs/`.
- Tutto ciò che è in `.doc/canonical/**` è generato/rigenerabile.

Comandi tipici:
- `py scripts/guardian.py sync`   (valida `docs/` e aggiorna indice/fingerprint)
- `py scripts/guardian.py lint`   (controlli struttura/coerenza)
- `py scripts/guardian.py derive` (genera `PROJ.md`, `TECH.md`, `DDT.md`)
- `py scripts/guardian.py next`   (genera prompt JIT dal TODO)
"""

TODO_TEMPLATE = """# TODO — Work Items (GUARDIAN)

## Work Items
- [OPEN] (Esempio) Stabilizzare GUARDIAN: policy “single source-of-truth” in `docs/`

## Scope corrente (allowlist concettuale)
- Specificare qui, in modo breve, cosa è in scope per il prossimo step.
"""

CURRENT_STATE_TEMPLATE = """# CURRENT_STATE — Stato corrente

- Updated: {updated}

## Note
- `docs/` è la **source-of-truth** dei canonici di progetto.
- `.doc/canonical/derived/` è la libreria operativa “compatta” generata da GUARDIAN.

## p0 (se usato)
- (facoltativo) Incolla qui il prompt operativo corrente o un link al file/prompt.
"""

LOGBOOK_TEMPLATE = """# LOGBOOK — Diario operativo

## {date}
- Init: creato scaffolding `.doc/` (GUARDIAN OPS)
"""

CANONICAL_LIBRARY_HEADER = """# CANONICAL_LIBRARY — Indice e fingerprint

Questo file è **generato** da GUARDIAN (`sync`/`derive`).
Non modificare manualmente.

"""


def ensure_base_structure(paths: GuardianPaths) -> None:
    # Create directories
    paths.doc_root.mkdir(parents=True, exist_ok=True)
    paths.canonical_dir.mkdir(parents=True, exist_ok=True)
    paths.derived_dir.mkdir(parents=True, exist_ok=True)
    paths.guardian_dir.mkdir(parents=True, exist_ok=True)

    # Operational folders (logs live under .doc/ to keep repo root clean)
    logs_dir = paths.doc_root / "ops" / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)
    gi = logs_dir / ".gitignore"
    if not gi.exists():
        # Keep encoding plain utf-8 (no BOM) for gitignore
        write_text_if_changed(
            gi,
            "# Auto-generated: ignore operational logs\n*.log\n*.txt\n",
            encoding="utf-8",
        )

    # Templates folder (safe to update; used as reference for new repos)
    templates_dir = paths.guardian_dir / "templates"
    templates_dir.mkdir(parents=True, exist_ok=True)
    write_text_if_changed(templates_dir / "TODO_TEMPLATE.md", TODO_TEMPLATE)
    write_text_if_changed(templates_dir / "CURRENT_STATE_TEMPLATE.md", CURRENT_STATE_TEMPLATE)
    write_text_if_changed(templates_dir / "LOGBOOK_TEMPLATE.md", LOGBOOK_TEMPLATE)
    write_text_if_changed(templates_dir / "README_TEMPLATE.md", README_TEMPLATE)

    # Operational files (STRICT non-destructive)
    if not paths.readme_file.exists():
        write_text_if_changed(paths.readme_file, README_TEMPLATE)
    if not paths.todo_file.exists():
        write_text_if_changed(paths.todo_file, TODO_TEMPLATE)
    if not paths.current_state_file.exists():
        write_text_if_changed(paths.current_state_file, CURRENT_STATE_TEMPLATE.format(updated=utc_now_iso()))
    if not paths.logbook_file.exists():
        write_text_if_changed(paths.logbook_file, LOGBOOK_TEMPLATE.format(date=datetime.now().date().isoformat()))

    # Ensure index exists (non-destructive)
    if not paths.index_file.exists():
        write_text_if_changed(paths.index_file, CANONICAL_LIBRARY_HEADER)


# ----------------------------
# Derived doc generators
# ----------------------------

def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig", errors="replace")


def extract_section(md: str, heading_regex: str) -> Optional[str]:
    """
    Very simple extractor: find a heading matching heading_regex and return until next same-or-higher heading.
    """
    # Normalize line endings
    md = md.replace("\r\n", "\n")
    lines = md.split("\n")

    # Find heading line index
    pattern = re.compile(heading_regex, re.IGNORECASE)
    start = None
    start_level = None

    for i, ln in enumerate(lines):
        m = re.match(r"^(#{1,6})\s+(.*)$", ln.strip())
        if not m:
            continue
        level = len(m.group(1))
        title = m.group(2).strip()
        if pattern.search(title):
            start = i
            start_level = level
            break

    if start is None or start_level is None:
        return None

    # Collect until next heading with level <= start_level
    out = [lines[start]]
    for j in range(start + 1, len(lines)):
        m = re.match(r"^(#{1,6})\s+.*$", lines[j].strip())
        if m and len(m.group(1)) <= start_level:
            break
        out.append(lines[j])

    return "\n".join(out).strip() + "\n"


def make_derived_header(title: str, sources: List[Path], paths: GuardianPaths, fingerprint: str) -> str:
    src_lines = "\n".join([f"- `{safe_rel(p, paths.repo_root)}`" for p in sources])
    return f"""# {title}

> GENERATED FILE — DO NOT EDIT  
> Source of truth: `./docs/`  
> Generated: {utc_now_iso()}  
> Fingerprint: {fingerprint}

## Sources
{src_lines}

---
"""


def derive_proj(paths: GuardianPaths, resolved_docs: List[Path], fingerprint: str) -> str:
    # Source docs
    ov = next((p for p in resolved_docs if p.name.startswith("001_")), None)
    pdr = next((p for p in resolved_docs if p.name.startswith("002_")), None)
    gaps = next((p for p in resolved_docs if p.name.startswith("009_")), None)

    sources = [p for p in [ov, pdr, gaps] if p is not None]
    header = make_derived_header("PROJ — Operational Project Brief", sources, paths, fingerprint)

    body = []
    if ov:
        ov_txt = read_text(ov)
        # Try extract a few useful sections; fallback to full summary block.
        for rx in [r"\bIn una frase\b", r"\bProblema\b", r"\bValore\b", r"\bPrincipi\b", r"\bUI\b", r"\bFasi\b"]:
            sec = extract_section(ov_txt, rx)
            if sec:
                body.append(sec)
        if not body:
            body.append("## Project Overview\n\n" + ov_txt.strip() + "\n")

    # Use-cases and acceptance from PDR
    if pdr:
        pdr_txt = read_text(pdr)
        sec = extract_section(pdr_txt, r"\bUse\s*Cases\b|\bCasi d'uso\b|\bUser\b|\bScenari\b")
        if sec:
            body.append(sec)
        sec2 = extract_section(pdr_txt, r"\bAcceptance\b|\bCriteri\b|\bDone\b|\bRequisiti\b")
        if sec2:
            body.append(sec2)

    # Gaps headline
    if gaps:
        gaps_txt = read_text(gaps)
        secg = extract_section(gaps_txt, r"\bGap\b|\bBacklog\b|\bManca\b")
        if secg:
            body.append(secg)

    # Operational UI mapping (lightweight template)
    body.append(
        """## UI — Operational Mapping (template)

Compila/raffina nei canonici di progetto (`docs/`) e rigenera con `guardian derive`.

| Pagina UI | A chi serve | Domanda tipica | Output |
|---|---|---|---|
| Decision Briefing | Retail | “Cosa faccio oggi?” | Lista segnali/ranking + disclosure |
| Gates & Data Quality | Retail/Dev | “I dati sono affidabili?” | Gate status + gaps |
| Audit Runs | Dev | “C’è look-ahead?” | Transcript + report |
| Forecast & Ranking | Retail | “Quali strumenti hanno miglior profilo?” | Stelle + confidence |
| NEWS-ALPHA | Retail | “Cosa muove il mercato?” | Sentiment + rating |
"""
    )

    return header + "\n\n".join(body).strip() + "\n"


def derive_tech(paths: GuardianPaths, resolved_docs: List[Path], fingerprint: str) -> str:
    pdd = next((p for p in resolved_docs if p.name.startswith("003_")), None)
    evidence = next((p for p in resolved_docs if p.name.startswith("008_")), None)
    trace = next((p for p in resolved_docs if p.name.startswith("005_")), None)

    sources = [p for p in [pdd, evidence, trace] if p is not None]
    header = make_derived_header("TECH — Operational Technical Brief", sources, paths, fingerprint)

    body = []

    if pdd:
        pdd_txt = read_text(pdd)
        for rx in [r"\bArchitettura\b|\bArchitecture\b", r"\bDataflow\b|\bPipeline\b", r"\bRunner\b|\bCLI\b", r"\bAudit\b|\bT\+1\b"]:
            sec = extract_section(pdd_txt, rx)
            if sec:
                body.append(sec)
        if not body:
            body.append("## PDD (full)\n\n" + pdd_txt.strip() + "\n")

    if evidence:
        ev_txt = read_text(evidence)
        se = extract_section(ev_txt, r"\bComandi\b|\bCommands\b|\bRunbook\b|\bOperativ")
        if se:
            body.append(se)

    # Inventory quick scan (scripts/pages) to keep doc aligned to repo shape
    scripts_dir = paths.repo_root / "scripts"
    pages_dir = paths.repo_root / "pages"
    src_dir = paths.repo_root / "src"

    def list_py(dir_path: Path, max_items: int = 50) -> List[str]:
        if not dir_path.exists():
            return []
        items = sorted([safe_rel(p, paths.repo_root) for p in dir_path.rglob("*.py") if p.is_file()])
        if len(items) > max_items:
            items = items[:max_items] + [f"... (+{len(items)-max_items} more)"]
        return items

    inv = []
    inv.append("## Repo Inventory (auto)\n")
    inv.append("### scripts/\n" + "\n".join([f"- `{x}`" for x in list_py(scripts_dir)]) + "\n")
    inv.append("### pages/\n" + "\n".join([f"- `{x}`" for x in list_py(pages_dir)]) + "\n")
    inv.append("### src/\n" + "\n".join([f"- `{x}`" for x in list_py(src_dir)]) + "\n")
    body.append("\n".join(inv))

    return header + "\n\n".join(body).strip() + "\n"


def derive_ddt(paths: GuardianPaths, resolved_docs: List[Path], fingerprint: str) -> str:
    ddt = next((p for p in resolved_docs if p.name.startswith("004_")), None)
    sources = [p for p in [ddt] if p is not None]
    header = make_derived_header("DDT — Operational Data Dictionary", sources, paths, fingerprint)

    if not ddt:
        return header + "## Missing\n\n`004_DDT_DATADICTIONARY.md` not found in `docs/`.\n"

    txt = read_text(ddt)

    # Try to extract key sections if present; else include entire doc.
    parts = []
    for rx in [r"\bSchema\b|\bTabelle\b|\bTables\b", r"\bColonne\b|\bColumns\b", r"\bVincoli\b|\bConstraints\b", r"\bSemantica\b|\bSemantics\b", r"\bTimezone\b|\bAs-of\b|\bGranular"]:
        sec = extract_section(txt, rx)
        if sec:
            parts.append(sec)

    if not parts:
        parts.append(txt.strip())

    # Add practical queries section (retail-friendly but engineering-grade)
    parts.append(
        """## Practical DuckDB Queries (template)

> Aggiorna nei canonici di progetto e rigenera con `guardian derive`.

- Elenco tabelle:
  - `SHOW TABLES;`
- Schema tabella:
  - `DESCRIBE <table_name>;`
- Conteggio righe e range date:
  - `SELECT MIN(date), MAX(date), COUNT(*) FROM <table>;`
"""
    )

    return header + "\n\n".join(parts).strip() + "\n"


def write_derived(paths: GuardianPaths, resolved_docs: List[Path], fingerprint: str) -> Tuple[int, int]:
    """
    Generate derived library files.
    Returns (written_count, no_op_count)
    """
    paths.derived_dir.mkdir(parents=True, exist_ok=True)

    outputs = [
        (paths.derived_dir / "PROJ.md", derive_proj(paths, resolved_docs, fingerprint)),
        (paths.derived_dir / "TECH.md", derive_tech(paths, resolved_docs, fingerprint)),
        (paths.derived_dir / "DDT.md", derive_ddt(paths, resolved_docs, fingerprint)),
    ]

    written = 0
    noop = 0
    for p, content in outputs:
        if write_text_if_changed(p, content):
            written += 1
        else:
            noop += 1
    return written, noop


# ----------------------------
# Index generator
# ----------------------------

def build_canonical_library(paths: GuardianPaths, project_docs: List[Path], fingerprint: str) -> str:
    lines = [CANONICAL_LIBRARY_HEADER]
    lines.append(f"- Updated: {utc_now_iso()}")
    lines.append(f"- Mode: **single source-of-truth** (`docs/`), no mirror copies in `.doc/`")
    lines.append(f"- Project docs fingerprint: `{fingerprint}`")
    lines.append("")
    lines.append("## Project canonicals (source of truth)")
    for p in project_docs:
        lines.append(f"- `{safe_rel(p, paths.repo_root)}`  (sha256: `{sha256_file(p)[:16]}`)")
    lines.append("")
    lines.append("## Derived operational library (generated)")
    if paths.derived_dir.exists():
        derived_files = sorted([p for p in paths.derived_dir.glob("*.md") if p.is_file()])
        if derived_files:
            for p in derived_files:
                lines.append(f"- `{safe_rel(p, paths.repo_root)}`  (sha256: `{sha256_file(p)[:16]}`)")
        else:
            lines.append("- (none yet) run `guardian derive`")
    else:
        lines.append("- (missing derived dir) run `guardian init`")
    lines.append("")
    lines.append("## Notes")
    lines.append("- Edit canonicals only in `docs/`.")
    lines.append("- Do not edit anything under `.doc/canonical/**` manually.")
    lines.append("")
    return "\n".join(lines).strip() + "\n"


# ----------------------------
# Commands
# ----------------------------

def cmd_init(paths: GuardianPaths, args: argparse.Namespace) -> int:
    ensure_base_structure(paths)
    print("DONE: init completato (template .doc/ presenti).")
    return 0


def cmd_sync(paths: GuardianPaths, args: argparse.Namespace) -> int:
    ensure_base_structure(paths)

    # Optional cleanup of legacy mirror folder
    legacy_mirror = paths.canonical_dir / "project"
    if args.clean and legacy_mirror.exists():
        shutil.rmtree(legacy_mirror)
        print(f"INFO: removed legacy mirror folder: {safe_rel(legacy_mirror, paths.repo_root)}")

    project_docs, missing = collect_project_docs(paths)
    if missing:
        for m in missing:
            print(f"ERROR: {m}")
        return 2

    fingerprint = compute_fingerprint(project_docs, paths.repo_root)
    idx = build_canonical_library(paths, project_docs, fingerprint)
    changed = write_text_if_changed(paths.index_file, idx)

    print(f"DONE: sync completato. mode=direct, docs={len(project_docs)}, index_updated={1 if changed else 0}, fingerprint={fingerprint}…")
    return 0


def cmd_lint(paths: GuardianPaths, args: argparse.Namespace) -> int:
    ensure_base_structure(paths)

    errors: List[str] = []
    warnings: List[str] = []

    # Structure checks
    if not paths.docs_dir.exists():
        errors.append(f"Missing required directory: {safe_rel(paths.docs_dir, paths.repo_root)}")

    # Disallow mirror folder (confusion source)
    legacy_mirror = paths.canonical_dir / "project"
    if legacy_mirror.exists():
        warnings.append(
            f"Legacy mirror folder exists: {safe_rel(legacy_mirror, paths.repo_root)}. "
            f"This setup uses direct mode; consider `guardian sync --clean`."
        )

    # Required docs checks
    project_docs, missing = collect_project_docs(paths)
    if missing:
        errors.extend(missing)

    # Derived allowlist checks
    allowed_derived = {"PROJ.md", "TECH.md", "DDT.md"}
    if paths.derived_dir.exists():
        for p in paths.derived_dir.glob("*.md"):
            if p.is_file() and p.name not in allowed_derived:
                warnings.append(f"Unexpected derived file: {safe_rel(p, paths.repo_root)} (allowed: {sorted(allowed_derived)})")

    # Basic index presence
    if not paths.index_file.exists():
        warnings.append(f"Missing index file: {safe_rel(paths.index_file, paths.repo_root)} (run `guardian sync`)")

    if errors:
        for e in errors:
            print(f"FAIL: {e}")
        for w in warnings:
            print(f"WARN: {w}")
        return 2

    for w in warnings:
        print(f"WARN: {w}")

    print("PASS: docs e canonici operativi risultano coerenti (direct mode).")
    return 0


def cmd_derive(paths: GuardianPaths, args: argparse.Namespace) -> int:
    ensure_base_structure(paths)

    project_docs, missing = collect_project_docs(paths)
    if missing:
        for m in missing:
            print(f"ERROR: {m}")
        return 2

    fingerprint = compute_fingerprint(project_docs, paths.repo_root)

    written, noop = write_derived(paths, project_docs, fingerprint)

    # Update index with derived listing (optional but useful)
    idx = build_canonical_library(paths, project_docs, fingerprint)
    write_text_if_changed(paths.index_file, idx)

    if written == 0:
        print("OK: derived library invariata (no-op).")
    else:
        print(f"DONE: derived library aggiornata. written={written}, no_op={noop}, fingerprint={fingerprint}…")
    return 0


def cmd_status(paths: GuardianPaths, args: argparse.Namespace) -> int:
    ensure_base_structure(paths)

    project_docs, missing = collect_project_docs(paths)
    if missing:
        print("STATUS: incomplete (missing required docs).")
        for m in missing:
            print(f"- {m}")
        return 1

    fingerprint = compute_fingerprint(project_docs, paths.repo_root)
    derived_files = sorted([p for p in paths.derived_dir.glob("*.md") if p.is_file()])

    print("STATUS: GUARDIAN OPS (direct mode)")
    print(f"- docs_dir: {safe_rel(paths.docs_dir, paths.repo_root)} ({len(project_docs)} required docs resolved)")
    print(f"- derived_dir: {safe_rel(paths.derived_dir, paths.repo_root)} ({len(derived_files)} files)")
    print(f"- fingerprint: {fingerprint}…")
    return 0


def cmd_programme(paths: GuardianPaths, args: argparse.Namespace) -> int:
    """
    Minimal "programme" placeholder: writes a short operational plan into CURRENT_STATE (non-destructive).
    """
    ensure_base_structure(paths)

    stamp = utc_now_iso()
    block = f"""

## Programme (auto)
- Generated: {stamp}
- Next steps:
  1) Update canonicals in `docs/` (single source-of-truth)
  2) Run: `guardian sync`, `guardian lint`, `guardian derive`
  3) Use `guardian next` to generate p0 from TODO scope
"""
    # Append if not already present
    existing = paths.current_state_file.read_text(encoding="utf-8", errors="replace")
    if "## Programme (auto)" in existing:
        print("OK: programme invariato (no-op).")
        return 0

    updated = existing.rstrip() + "\n" + block.lstrip()
    write_text_if_changed(paths.current_state_file, updated)
    print("DONE: programme scritto in CURRENT_STATE.md.")
    return 0


# ----------------------------
# CLI
# ----------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="guardian_ops.py", add_help=True)
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("init", help="Initialize .doc/ scaffolding (non-destructive).")

    sp_sync = sub.add_parser("sync", help="Validate docs/ and update .doc/CANONICAL_LIBRARY.md (no copy).")
    sp_sync.add_argument("--clean", action="store_true", help="Remove legacy mirror folder .doc/canonical/project if present.")

    sub.add_parser("lint", help="Check structure and required docs; warns on legacy mirror.")
    sub.add_parser("derive", help="Generate derived operational library (.doc/canonical/derived/*).")
    sub.add_parser("status", help="Show current status summary.")
    sub.add_parser("programme", help="Write a small operational plan into CURRENT_STATE.md (optional).")

    return p


def main(argv: List[str]) -> int:
    paths = default_paths()
    parser = build_parser()
    args = parser.parse_args(argv)

    cmd = args.cmd
    if cmd == "init":
        return cmd_init(paths, args)
    if cmd == "sync":
        return cmd_sync(paths, args)
    if cmd == "lint":
        return cmd_lint(paths, args)
    if cmd == "derive":
        return cmd_derive(paths, args)
    if cmd == "status":
        return cmd_status(paths, args)
    if cmd == "programme":
        return cmd_programme(paths, args)

    print(f"ERROR: Unknown command: {cmd}")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
